In [2]:
import pandas as pd

onboarding = pd.read_csv(
    "../data/external/ki_endolist/ki-dataset/Patient_onboarding_info.csv"
)

print(onboarding.shape)
print(onboarding.columns.tolist())

onboarding.head()

(34, 30)
['User id', 'Age at first period', 'Age at first endo symptoms', 'Age at endo dx', 'Age', 'BMI', 'Period bleeding days', 'Cycle length', 'Family history', 'Marital status', 'Effect on relationships', 'Occupation', 'Work status', 'Education', 'Infertility problem', 'Adenomyosis', 'Diagnostic surgery', 'Number of surgeries', 'Removal of lesions', 'Lesion type', 'Affected organs', 'Diagnosed by endo physician', 'Hormonal therapy', 'Regular period', 'Comorbidities', 'Regular meds', 'Mental health meds', 'Sleep meds', 'Pain meds', 'Alternative therapy']

,User id,Age at first period,Age at first endo symptoms,Age at endo dx,Age,BMI,Period bleeding days,Cycle length,Family history,Marital status,...,Affected organs,Diagnosed by endo physician,Hormonal therapy,Regular period,Comorbidities,Regular meds,Mental health meds,Sleep meds,Pain meds,Alternative therapy
0,38,11.0,NaN,30.0,37,23.437500,5.0,30.0,4,1,...,NaN,1.0,2,1,31,NaN,4.0,4,NaN,"2, 3, 4, 6"
1,39,11.0,15.0,21.0,29,29.733900,4.5,30.0,0,3,...,NaN,1.0,2,1,31,1,4.0,4,"4, 2",1
2,41,12.5,NaN,33.0,34,23.667800,2.5,28.0,0,1,...,NaN,1.0,2,1,31,NaN,4.0,4,"4, 5","1, 2, 3, 4, 8"
3,42,12.0,12.0,29.0,33,22.546576,5.0,26.0,4,2,...,NaN,1.0,2,2,31,NaN,4.0,1,"2, 4, 5",16
4,44,13.0,13.0,31.0,33,21.082813,5.0,31.5,6,3,...,NaN,1.0,2,1,31,12,4.0,4,"2, 3, 5","1, 2, 3, 4, 5, 6, 7, 8"

In [3]:
user38 = pd.read_csv(
    "../data/external/ki_endolist/ki-dataset/User38.csv"
)

print(user38.shape)
print(user38.columns.tolist())

user38.head()

(355, 24)
['User id', 'Day in study', 'Week day', 'Cycle number', 'Cycle day', 'First day of period', 'Period (0-no, 1-yes)', 'Migraines (0-no pain, 4-worst pain)', 'Period pain (0-no pain, 4-worst pain)', 'Type of stool (0-no stool, 7-bowel blockage)', 'General emotional condition (1-bad, 10-amazing)', 'General physical condition (1-bad, 10-amazing)', 'Breast tenderness (0-no pain, 4-worst pain)', 'Energy (0-no energy, 4-most energy)', 'Painful bowel movement (0-no pain, 4-worst pain)', 'Desire to eat sweet food (0-no appetite, 4-most appetite)', 'Lower back pain and pelvic pain (0-no pain, 4-worst pain)', 'Lower abdominal stabbing pain / abdominal cramps (0-no pain, 4-worst pain)', 'Ovulation pain (0-no pain, 4-worst pain)', 'Paracetamol (times)', 'Ovulation test values (0.0-4.0)', 'Knee pain (0-no pain, 4-worst pain)', 'Pain in ankle (0-no pain, 4-worst pain)', 'Sick day (0-no, 1-yes)']

,User id,Day in study,Week day,Cycle number,Cycle day,First day of period,"Period (0-no, 1-yes)","Migraines (0-no pain, 4-worst pain)","Period pain (0-no pain, 4-worst pain)","Type of stool (0-no stool, 7-bowel blockage)",...,"Painful bowel movement (0-no pain, 4-worst pain)","Desire to eat sweet food (0-no appetite, 4-most appetite)","Lower back pain and pelvic pain (0-no pain, 4-worst pain)","Lower abdominal stabbing pain / abdominal cramps (0-no pain, 4-worst pain)","Ovulation pain (0-no pain, 4-worst pain)",Paracetamol (times),Ovulation test values (0.0-4.0),"Knee pain (0-no pain, 4-worst pain)","Pain in ankle (0-no pain, 4-worst pain)","Sick day (0-no, 1-yes)"
0,38,1,Sat,1.0,1,1.0,1.0,0.0,1.0,5.0,...,1.0,0.0,2.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
1,38,2,Sun,1.0,2,0.0,1.0,0.0,1.0,5.0,...,0.0,0.0,1.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
2,38,3,Mon,1.0,3,0.0,1.0,0.0,0.0,5.0,...,1.0,0.0,1.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
3,38,4,Tue,1.0,4,0.0,0.0,0.0,0.0,4.0,...,0.0,0.0,1.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
4,38,5,Wed,1.0,5,0.0,0.0,0.0,0.0,6.0,...,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN

In [4]:
onboarding.columns.tolist()

['User id',
 'Age at first period',
 'Age at first endo symptoms',
 'Age at endo dx',
 'Age',
 'BMI',
 'Period bleeding days',
 'Cycle length',
 'Family history',
 'Marital status',
 'Effect on relationships',
 'Occupation',
 'Work status',
 'Education',
 'Infertility problem',
 'Adenomyosis',
 'Diagnostic surgery',
 'Number of surgeries',
 'Removal of lesions',
 'Lesion type',
 'Affected organs',
 'Diagnosed by endo physician',
 'Hormonal therapy',
 'Regular period',
 'Comorbidities',
 'Regular meds',
 'Mental health meds',
 'Sleep meds',
 'Pain meds',
 'Alternative therapy']

In [5]:
onboarding.head()

,User id,Age at first period,Age at first endo symptoms,Age at endo dx,Age,BMI,Period bleeding days,Cycle length,Family history,Marital status,...,Affected organs,Diagnosed by endo physician,Hormonal therapy,Regular period,Comorbidities,Regular meds,Mental health meds,Sleep meds,Pain meds,Alternative therapy
0,38,11.0,NaN,30.0,37,23.437500,5.0,30.0,4,1,...,NaN,1.0,2,1,31,NaN,4.0,4,NaN,"2, 3, 4, 6"
1,39,11.0,15.0,21.0,29,29.733900,4.5,30.0,0,3,...,NaN,1.0,2,1,31,1,4.0,4,"4, 2",1
2,41,12.5,NaN,33.0,34,23.667800,2.5,28.0,0,1,...,NaN,1.0,2,1,31,NaN,4.0,4,"4, 5","1, 2, 3, 4, 8"
3,42,12.0,12.0,29.0,33,22.546576,5.0,26.0,4,2,...,NaN,1.0,2,2,31,NaN,4.0,1,"2, 4, 5",16
4,44,13.0,13.0,31.0,33,21.082813,5.0,31.5,6,3,...,NaN,1.0,2,1,31,12,4.0,4,"2, 3, 5","1, 2, 3, 4, 5, 6, 7, 8"

In [6]:
user38.columns.tolist()

['User id',
 'Day in study',
 'Week day',
 'Cycle number',
 'Cycle day',
 'First day of period',
 'Period (0-no, 1-yes)',
 'Migraines (0-no pain, 4-worst pain)',
 'Period pain (0-no pain, 4-worst pain)',
 'Type of stool (0-no stool, 7-bowel blockage)',
 'General emotional condition (1-bad, 10-amazing)',
 'General physical condition (1-bad, 10-amazing)',
 'Breast tenderness (0-no pain, 4-worst pain)',
 'Energy (0-no energy, 4-most energy)',
 'Painful bowel movement (0-no pain, 4-worst pain)',
 'Desire to eat sweet food (0-no appetite, 4-most appetite)',
 'Lower back pain and pelvic pain (0-no pain, 4-worst pain)',
 'Lower abdominal stabbing pain / abdominal cramps (0-no pain, 4-worst pain)',
 'Ovulation pain (0-no pain, 4-worst pain)',
 'Paracetamol (times)',
 'Ovulation test values (0.0-4.0)',
 'Knee pain (0-no pain, 4-worst pain)',
 'Pain in ankle (0-no pain, 4-worst pain)',
 'Sick day (0-no, 1-yes)']

In [7]:
user38.head()

,User id,Day in study,Week day,Cycle number,Cycle day,First day of period,"Period (0-no, 1-yes)","Migraines (0-no pain, 4-worst pain)","Period pain (0-no pain, 4-worst pain)","Type of stool (0-no stool, 7-bowel blockage)",...,"Painful bowel movement (0-no pain, 4-worst pain)","Desire to eat sweet food (0-no appetite, 4-most appetite)","Lower back pain and pelvic pain (0-no pain, 4-worst pain)","Lower abdominal stabbing pain / abdominal cramps (0-no pain, 4-worst pain)","Ovulation pain (0-no pain, 4-worst pain)",Paracetamol (times),Ovulation test values (0.0-4.0),"Knee pain (0-no pain, 4-worst pain)","Pain in ankle (0-no pain, 4-worst pain)","Sick day (0-no, 1-yes)"
0,38,1,Sat,1.0,1,1.0,1.0,0.0,1.0,5.0,...,1.0,0.0,2.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
1,38,2,Sun,1.0,2,0.0,1.0,0.0,1.0,5.0,...,0.0,0.0,1.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
2,38,3,Mon,1.0,3,0.0,1.0,0.0,0.0,5.0,...,1.0,0.0,1.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
3,38,4,Tue,1.0,4,0.0,0.0,0.0,0.0,4.0,...,0.0,0.0,1.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
4,38,5,Wed,1.0,5,0.0,0.0,0.0,0.0,6.0,...,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN